version: '3'
    
services:

  web:
    image: rytakimoto/livra_web:prod
    ports:
      - "80:3000"
    env_file:
      - .env/production/database
      - .env/production/web

  redis:
      image: redis

  database:
    image: postgres:9.6
    env_file:
      - .env/production/database
    volumes:
      - db_data:/var/lib/postgresql/data

  visualizer:
    image: dockersamples/visualizer:stable
    ports:                                             
      - "8080:8080"                                    
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"     
    deploy:                                            
      placement:
        constraints: [node.role == manager]            

  db-migrator:
    image: rytakimoto/livra_web:prod
    command: ["./wait-for", "--timeout=300", "database:5432", "--",   
              "bin/rails", "db:migrate"]   
    env_file:
      - .env/production/database
      - .env/production/web
    deploy:
      restart_policy:    
        condition: none

volumes:
  db_data: